on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: job to test push action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use root action
        uses: ./ # Uses an action in the root directory
        id: push
        with:
          path: ./tests/test_app.wick
          latest: "true"
          username: ${{ secrets.CANDLE_REGISTRY_USERNAME }}
          password: ${{ secrets.CANDLE_REGISTRY_PASSWORD }}